import type { NextPage } from "next";
import Head from "next/head";
import Body from "../components/body";
import TopBar from "../components/topBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CMS-tos -home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <TopBar/>
          <Body /> 
        </main>
    </>
  );
};

export default Home;
